meta:
  engine: 4.1.0
units:
  kx: cx
  ky: cy
  px: kx + 4
  py: ky + 4
points:
  zones:
    matrix:
      key:
        padding: 1ky + 1
        spread: 1kx + 1
      anchor:
        rotate: 8
        shift: [ 100,-100]
      columns:
        outer:
          key.col_net: P4
        pinky:
          key.col_net: P5
        ring:
          key.splay: -5
          key.origin: [-12, -19]
          key.stagger: 12
          key.col_net: P6
        middle:
          key.stagger: 5
          key.col_net: P7
        index:
          key.stagger: -6
          key.col_net: P8
        inner:
          key.stagger: -2
          key.col_net: P9
      rows:
        bottom:
          row_net: P19
          mirror.row_net: P2
        home:
          row_net: P20
          mirror.row_net: P0
        top:
          row_net: P21
          mirror.row_net: P1
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-15, -20]
      columns:
        near:
          key.col_net: P7
        home:
          key.spread: 21.25
          key.splay: -5
          key.origin: [-11.75, -9]
          key.col_net: P8
        far:
          key.spread: 21.25
          key.splay: -15
          key.origin: [-9.5, -9]
          key.col_net: P9
      rows:
        thumb:
          row_net: P18
          mirror.row_net: P3

  rotate: -20
  mirror:
    ref: matrix_pinky_home
    distance: 12kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px,py]
  keys:
    - what: rectangle
      where: true
      size: [ kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_bottom
          shift: [ -0.5px,-0.5py]
        - ref: matrix_outer_top
          shift: [-0.5px, +0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5px,+0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, +0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, +0.5py]
        - ref: matrix_middle_top
          shift: [ 0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [0.5px, +0.5py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px, +0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px, +0.5py]
        - ref: mirror_matrix_outer_top
          shift: [-0.5px, +0.5py]
        - ref: mirror_matrix_outer_bottom
          shift : [ -0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_ring_bottom
          shift: [-0.25px,-1py]
        - ref: mirror_matrix_middle_bottom
          shift: [-0.5px,-1py]
        - ref: mirror_thumbfan_near_thumb
          shift: [ -0.5px, -0.5py]
        - ref: mirror_thumbfan_home_thumb
          shift: [ -0.5px, -0.5py]
        - ref: mirror_thumbfan_far_thumb
          shift: [ -0.5px, -0.5py]
        - ref: mirror_thumbfan_far_thumb
          shift: [ 0.5px, -0.5py]
        - ref: thumbfan_far_thumb
          shift: [ 0.5px, -0.5py]
        - ref: thumbfan_far_thumb
          shift: [ -0.5px, -0.5py]
        - ref: thumbfan_home_thumb
          shift: [ -0.5px,-0.5py]
        - ref: thumbfan_near_thumb
          shift: [ -0.5px, -0.5py]
        - ref: matrix_middle_bottom
          shift: [-0.5px,-1py]
        - ref: matrix_ring_bottom
          shift: [-0.25px,-1py]




      fillet: 2
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  main:
    template: kicad8
    outlines:
      main:
        outline: board

    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust: 
          shift: [ 0,-5]
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          side: "B"
        where:
          ref.aggregate.parts: [ matrix_inner_top, mirror_matrix_inner_top]
          shift: [ 0,0]
          rotate: 0
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref.aggregate.parts: [ matrix_inner_bottom, mirror_matrix_inner_bottom]
          shift: [ 0,-1]
          rotate: -90
      battery:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          side: "F"
          BAT_P: VCC
          BAT_N: GND
        where:
          ref.aggregate.parts: [ matrix_inner_bottom, mirror_matrix_inner_bottom]
          shift: [ -1,-1]
          rotate: 0

      nice_view:
        what: ceoloide/display_nice_view
        params:
          side: "F"

        where:
          ref.aggregate.parts: [matrix_inner_home, mirror_matrix_inner_home]
          shift: [ 0,0]
          rotate: -90

### outer most holes
      hole_top_left:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_outer_top
          shift: [0.54kx,-0.4ky]

      hole_top_right:
        what: ceoloide/mounting_hole_plated
        where:
          ref: mirror_matrix_outer_top
          shift: [0.54kx,-0.4ky]

      hole_bottom_left:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_outer_bottom 
          shift: [0.54kx,-0.4ky]

      hole_bottom_right:
        what: ceoloide/mounting_hole_plated
        where:
          ref: mirror_matrix_outer_bottom 
          shift: [0.54kx,-0.4ky]
### holes under the pinky
      hole_ring_top_left:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_ring_top
          shift: [0.54kx,-0.1ky]

      hole_ring_bottom_left:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_ring_bottom 
          shift: [0.54kx,-0.1ky]

      hole_ring_top_right:
        what: ceoloide/mounting_hole_plated
        where:
          ref: mirror_matrix_ring_top
          shift: [0.54kx,-0.1ky]

      hole_ring_bottom_right:
        what: ceoloide/mounting_hole_plated
        where:
          ref: mirror_matrix_ring_bottom 
          shift: [0.54kx,-0.1ky]
### holes in the center
      hole_top_inner_left:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_inner_top 
          shift: [0.44kx,-0.52ky]

      hole_top_inner_right:
        what: ceoloide/mounting_hole_plated
        where:
          ref: mirror_matrix_inner_top 
          shift: [0.44kx,-0.52ky]


## hole in the thumbcluster
      hole_bottom_thumb_left:
         what: ceoloide/mounting_hole_plated
         where:
           ref: thumbfan_home_thumb
           shift: [0.65kx,-0.1ky]

      hole_bottom_thumb_right:
         what: ceoloide/mounting_hole_plated
         where:
           ref: mirror_thumbfan_home_thumb
           shift: [0.65kx,-0.1ky]
